version: "3.9"

services:
  web-client:
    build: .
    container_name: sltcestloic-web-client
    ports:
      - "4200:4200"
    restart: always
    networks:
      - caddy

networks:
   caddy:
      external: true