version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: sltcestloic-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  server:
    build:
      context: .
      dockerfile: ./src/server/Dockerfile
    container_name: sltcestloic-server
    environment:
      PORT: ${PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TYPEORM_SYNCHRONIZE: ${TYPEORM_SYNCHRONIZE}
      CORS_ORIGIN: ${CORS_ORIGIN}
    ports:
      - "127.0.0.1:3001:3000"
    depends_on:
      - postgres
    restart: always

  client:
    build:
      context: .
      dockerfile: ./src/client/Dockerfile
    container_name: sltcestloic-client
    ports:
      - "127.0.0.1:4200:4200"
    restart: always

volumes:
  postgres-data:
