version: "3"

services:
  sltcestloic:
    build: .
    volumes:
      - ./src:/app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.sltcestloic-secure.entrypoints=websecure"
      - "traefik.http.routers.sltcestloic-secure.rule=Host(`www.sltcestloic.dev`, `sltcestloic.dev`)"
      - "traefik.http.routers.sltcestloic-secure.tls=true"
      - "traefik.http.routers.sltcestloic-secure.tls.certresolver=letsencrypt"
    restart: always